 - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    yum: 
      name:
        - httpd
        - php 
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache, centos, httpd
    service: 
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"
