#base
---
- name: install updates (CentOS)
  tags: always
  yum:
    name: "*"
  when: ansible_distribution == "CentOS"

- name: install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

